name: Terraform Workflow

on:
  push:                       # Trigger plan on every push
    branches:
      - "**"
  pull_request:               # Trigger apply when a pull request is merged
    types: [closed]
  workflow_dispatch:          # Allow manual trigger for destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Step 3: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 4: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 5: Terraform Plan (on Push)
      - name: Terraform Plan
        if: github.event_name == 'push'
        run: terraform plan -var "subscription_id=$ARM_SUBSCRIPTION_ID" \
                            -var "client_id=$ARM_CLIENT_ID" \
                            -var "client_secret=$ARM_CLIENT_SECRET" \
                            -var "tenant_id=$ARM_TENANT_ID"

      # Step 6: Terraform Apply (on PR Merge)
      - name: Terraform Apply
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: terraform apply -auto-approve -var "subscription_id=$ARM_SUBSCRIPTION_ID" \
                                         -var "client_id=$ARM_CLIENT_ID" \
                                         -var "client_secret=$ARM_CLIENT_SECRET" \
                                         -var "tenant_id=$ARM_TENANT_ID"

      # Step 7: Terraform Destroy (Manual Trigger)
      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve -var "subscription_id=$ARM_SUBSCRIPTION_ID" \
                                              -var "client_id=$ARM_CLIENT_ID" \
                                              -var "client_secret=$ARM_CLIENT_SECRET" \
                                              -var "tenant_id=$ARM_TENANT_ID"
